springdoc.api-docs.enabled=${SPRINGDOC_ENABLED:true}
springdoc.swagger-ui.enabled=${SWAGGER_UI_ENABLED:${SPRINGDOC_ENABLED:true}}
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.persist-authorization=false
spring.profiles.default=local, oauth
spring.config.import=optional:file:.env[.properties],optional:file:../.env[.properties],optional:file:../../.env[.properties]
